### ISSUE TITLE
Any scope for OSX?

### ISSUE THREAD

**Issue by sga-girdhari** [KevinWang15/PsVDecrypt#10]
Hi,

I would like to use this tool on OSX, any idea for that?

OSX have different DB file and directory structure from windows.

Thanks.

**Comment by KevinWang15** [comment]
Sorry, since I don't have a Mac computer, there's currently no plan for an OSX version. Try using Boot Camp on OSX or launch a windows VM on AWS

**Comment by sga-girdhari** [comment]
Okay Thanks, I will try to create a script for mac.
