### ISSUE TITLE
Can you please explain the steps involved in creating mp4 files from encypted files?

### ISSUE THREAD

**Issue by sathishkumar-kb** [KevinWang15/PsVDecrypt#12]
I am planning to create desktop application using Electron. I would like to know the steps involved for converting to MP4 files from PSV files.

**Comment by KevinWang15** [comment]
This project is open-source, isn't it
You may take a look at [Program.cs](https://github.com/KevinWang15/PsVDecrypt/blob/master/Program.cs), all the steps involved are in this file.
Basically the steps are 
1. collect course info from offline player's sqlite database  
2. apply xor operation on .psv files to turn them into .mp4 files (.psv files only use xor cipher so there's no transcoding, see [VideoEncryption.cs](https://github.com/KevinWang15/PsVDecrypt/blob/master/Domain/VideoEncryption.cs))
3. generate folder structure / .srt files / etc.

**Comment by KevinWang15** [comment]
If you manage to port it to Node.js / create a good GUI, be sure to let me know.
There are many users complaining about lack of GUI and MacOS support.
