### ISSUE TITLE
How did you work out how to decrypt the PSV files?

### ISSUE THREAD

**Issue by kamyuen** [KevinWang15/PsVDecrypt#17]
The application seems to work great and I am able to understand the code. However I would like to know how you found out how to decrypt the PSV files in the first place.
Opening the PSV files in a text editor obviously results in weird characters being displayed as it seems to be a binary file. Looking at the Sqlite DB I see a bunch of tokens etc. but no real clue that I can see to start decrypting these files.
So what was the process to discover the steps required?
I'm really curious and want to learn.

**Comment by Kang-Jack** [comment]
should be a secret of author :P but may be decode offline player binary files ,is one of answer i guess

**Comment by KevinWang15** [comment]
Just reverse engineer the offline player :D 
It's very easy. You may use tools like dotPeek
