### ISSUE TITLE
linkedin learning

### ISSUE THREAD

**Issue by joelmute** [KevinWang15/PsVDecrypt#20]
https://github.com/mclmza/linkedin-learning-downloader
can you modify ,,,so that it can download linkedin tutorials
I failed to use it ..in that format

**Comment by KevinWang15** [comment]
Sorry, this project is not related to ```linkedin-learning-downloader```, you may wish to open an issue there if you need support.

**Comment by KevinWang15** [comment]
LinkedIn and PS use very different systems.
```linkedin-learning-downloader``` is a scraper while ```PsVDecrypt``` is a decryptor.
So they are very different, and it's not possible to modify one project to use it on the other site.
