### ISSUE TITLE
SQLite DB seems empty

### ISSUE THREAD

**Issue by bonobonohu** [KevinWang15/PsVDecrypt#3]
hi, thanks for your work. i have an issue with the pluralsight.db SQLite file. it definitely contains data, but for some reason PsVDecrypt writes the message " > Error: cannot find course in database.".
i checked the db file with http://sqlitebrowser.org/ and got the same results: all tables have zero rows.
do you have an idea, what should happened?

**Comment by KevinWang15** [comment]
Not sure.. seems the program and sqlitebrowser.org has reached the same conclusion about there not being any data. Can there be duplicate installation of the offline player?
Try a fresh installation on another windows user or another windows machine. It seems to me that most people are able to use this tool without such problem.
