### ISSUE TITLE
 Possibility of selecting the language generated by the subtitle

### ISSUE THREAD

**Issue by Igao92** [KevinWang15/PsVDecrypt#4]
Hey ... good work here! Is it possible to choose in which language the ".SRT" file will be generated?

**Comment by KevinWang15** [comment]
Does PS offer subtitles in different languages now?
I'm not a subscriber now so I cannot check.
If it does, you may examine the content of ```%localAppData%\Pluralsight\pluralsight.db``` to see if you could find the subtitles in your desired language. Then modify the following part of the program accordingly to make it generate the .SRT in another language:

https://github.com/KevinWang15/PsVDecrypt/blob/3ffc19db964020e20f617cef70ac50d4827cd7bb/Program.cs#L175-L179

https://github.com/KevinWang15/PsVDecrypt/blob/3ffc19db964020e20f617cef70ac50d4827cd7bb/Program.cs#L189-L207
