### ISSUE TITLE
removed the course from offline player, still PSV files on my computer

### ISSUE THREAD

**Issue by nilipta** [KevinWang15/PsVDecrypt#6]
I accidentally cut the PSV files to another folder, then player shows download option. Then I restored back the files, however nothing happened helpful. then I removed the course icon from the player. Now how can i make use of those PSV files to convert, play or share? Please help me.

**Comment by KevinWang15** [comment]
This program automatically searches ```%AppData%``` for .psv files, moving the files back should work.
However, .psv files alone is not enough, it also reads important metadata from the sqlite database located in ```%AppData%``` (the same as the one offline player uses)
If the metadata in the database has been deleted by the offline player (you can no longer see the courses in the offline player), then this converter can no longer work. Please redownload the course.

(Strictly speaking, you can still decrypt those .psv files with ```DecryptFile```. But there will be no metadata, no subtitles, etc. It's just not worth the trouble)
https://github.com/KevinWang15/PsVDecrypt/blob/3ffc19db964020e20f617cef70ac50d4827cd7bb/Util.cs#L15-L24

**Comment by ErfanFarmer** [comment]
Hi first of all thanks for this great tool, I have been able to decrypt my present courses through it.

But I have one problem as you mentioned already that offline player maintains some metadata about the course so when you log out of the App it doesn't display the course again when you sign in, also the decrypt tool doesn't decrypt the psv files already sitting in the courses folder.

So it there any way to decrypt these psv files without this metadata using decrypt tool.

Thanks.

**Comment by KevinWang15** [comment]
@ErfanFarmer As is mentioned in the previous post, there is a util function called ``` DecryptFile(string srcFile, string dstFile) ``` in ```PsVDecrypt/Util.cs```, which you can call to decrypt psv files without metadata.
(You need to use VisualStudio to run the C# code)

I believe it's not worth the trouble, when you convert a course it's better to keep its subtitles and all other metadata. Isn't redownloading them easier?
